
# 日志配置
logging: 
  config: classpath:log4j2-spring.xml

# 容器配置
server: 
  port: 8889
  servlet: 
    context-path: /
    session.timeout: 0
  tomcat: 
    uri-encoding: UTF-8
    accept-count: 512
    min-spare-threads: 10
    max-connections: 10000
    max-threads: 500
    accesslog: 
      enabled: true
      buffered: true
      directory: /usr/local/logs/prometheus/cloud
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      request-attributes-enabled: true
      rotate: true
      suffix: .log
      background-processor-delay: 10s

# spring boot 配置
spring: 
  application:
    name: prometheus-springcloud
  profile:
    active: default
  mvc: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    servlet.load-on-startup: 1
    throw-exception-if-no-handler-found: true
  resources: 
    add-mappings: true
  jackson: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    joda-date-time-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
  servlet: 
    multipart: 
      enabled: true
      max-file-size: 20MB
      max-request-size: 24MB
      location: /usr/local/logs/prometheus/cloud
management: 
  endpoints: 
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: '*'
  metrics:
    tags: 
      application: ${spring.application.name}

# springcloud配置
spring.cloud:
  zookeeper:
    enabled: true
    connect-string: 192.168.140.130:2181
    max-retries: 10
    max-sleep-ms: 500
    discovery:
      enabled: true
      register: true
      prefer-ip-address: true
      root: /cloud
      metadata:
        cluster: mrh-cluster
        service: ${spring.application.name}
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000
  compression:
    request:
      enabled: true
      mime-types: application/json
      min-request-size: 1024
    response:
      enabled: true


