
# 日志配置
logging: 
  config: classpath:log4j2-spring.xml

# 容器配置
server: 
  port: 8888
  servlet: 
    context-path: /
    session.timeout: 0

# spring boot 配置
spring: 
  mvc: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    servlet.load-on-startup: 1
    throw-exception-if-no-handler-found: true
  resources: 
    add-mappings: true
  jackson: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    joda-date-time-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'

# springdoc
springdoc: 
  auto-tag-classes: false
  use-fqn: true
  cache.disabled: true
  swagger-ui: 
    enabled: true
  api-docs: 
    enabled: true
    path: /v3/api-docs


