
#####  直连单点 seata-server 配置
#####  docker run --name seata-server -it -d -p 8091:8091 -p 7091:7091 seataio/seata-server:1.5.0

logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 8889
  servlet: 
    context-path: /
    session.timeout: 0

spring: 
  application:
    name: mrh-spring-boot-transaction-seata-xa-user
  datasource: 
    url: 'jdbc:mysql://192.168.140.130:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8'
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 1
    max-active: 50
    min-idle: 1
    max-wait: 100
    pool-prepared-statements: false
    validation-query: 'select 1'
    validation-query-timeout: 1
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    keep-alive: false
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 600000

mybatis: 
  mapper-locations: classpath:org/lushen/mrh/boot/seata/at/dao/mapping/*.xml
  type-aliases-package: org.lushen.mrh.boot.seata.at.dao.model
  type-handlers-package: org.lushen.mrh.boot.seata.at.dao.handler

seata:
  enabled: true
  application-id: mrh-seata-xa-user
  tx-service-group: default_tx_group
  data-source-proxy-mode: XA
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 192.168.140.130:8091

