
logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 9557
  servlet: 
    context-path: /

spring:
  application:
    name: mrh-spring-cloud-service-prometheus
  jackson: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    joda-date-time-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization: 
      FAIL_ON_UNKNOWN_PROPERTIES: false
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    visibility:
      GETTER: NONE
      SETTER: NONE
      FIELD: ANY
  cloud: 
    zookeeper: 
      enabled: true
      connect-string: localhost:2181
      prefer-ip-address: true
      max-retries: 10
      max-sleep-ms: 500
      discovery: 
        enabled: true
        register: true
        root: /cloud

management:
  endpoints: 
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    beans.enabled: true
    caches.enabled: true
    conditions.enabled: true
    configprops.enabled: true
    env.enabled: true
    info.enabled: true
    loggers.enabled: true
    health.enabled: true
    heapdump.enabled: true
    threaddump.enabled: true
    scheduledtasks.enabled: true
    mappings.enabled: true
    prometheus.enabled: true
    metrics.enabled: true
    serviceregistry.enabled: true
  metrics:
    tags: 
      cluster: mrh-cluster
      application: java
      service: ${spring.application.name}


