
logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 9500
  servlet: 
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 512
    min-spare-threads: 5
    max-threads: 100
    max-connections: 200
    accesslog:
      enabled: true
      buffered: true
      directory: /usr/local/logs/mrh/cloud/config
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      request-attributes-enabled: true
      rotate: true
      suffix: .log
      background-processor-delay: 10s

spring:
  application:
    name: mrh-spring-cloud-config
  security:
    user:
      name: root
      password: 123456
  profiles:
    active: native
  cloud: 
    config:
      server:
        native: 
          search-locations: 
            - classpath:/config
            # - file:./config/
            # - file:/usr/local/application/config
            # - file:///E:/config




