
logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 18888

spring:
  application:
    name: mrh-spring-cloud-service-bootadmin-server
  security:
    user:
      name: "admin"
      password: "123456"
  cloud: 
    zookeeper: 
      enabled: true
      connect-string: 192.168.140.136:2181
      prefer-ip-address: true
      max-retries: 10
      max-sleep-ms: 500
      discovery: 
        enabled: true
        register: false
        root: /cloud
    discovery:
      client:
        simple:
          instances: 
            mrh-spring-cloud-api-simple:
            - uri: http://localhost:9529


