
# 日志配置
logging: 
  config: classpath:log4j2-spring.xml

# 容器配置
server: 
  port: 8888
  servlet: 
    context-path: /
    session.timeout: 0

# elasticjob
elasticjob:
  regCenter:
    serverLists: 192.168.140.136:2181
    namespace: mrh-spring-boot-elasticjob
  dump:
    port: 18080
  jobs:
    simpleJob:
      elasticJobClass: org.lushen.mrh.boot.elasticjob.demo.PrintSimpleJob
      jobBootstrapBeanName: org.lushen.mrh.boot.elasticjob.demo.PrintSimpleJob
      cron: 0/5 * * * * ?
      timeZone: GMT+08:00
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou