
logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 9538
  servlet: 
    context-path: /

spring:
  application:
    name: mrh-spring-cloud-service-bus-amqp
  jackson: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    joda-date-time-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization: 
      FAIL_ON_UNKNOWN_PROPERTIES: false
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    visibility:
      GETTER: NONE
      SETTER: NONE
      FIELD: ANY
  rabbitmq: 
    host: 127.0.0.1
    port: 5672
    username: MjphbXFwLWNuLXRsMzJycmEydzAwMTpMVEFJNXROTWZBZERkNGhvTmQ1MnJ3YkY=
    password: MUY5OTdGOUI2RTNCNkRCMDBEMUY5NkM1RDdGODRBRjM4QTk4MDU4ODoxNjU3MDYyNjkyODU1
    connection-timeout: 0
    publisher-confirms: true
    publisher-returns: true
  cloud: 
    zookeeper: 
      enabled: true
      connect-string: localhost:2181
      prefer-ip-address: true
      max-retries: 10
      max-sleep-ms: 500
      discovery: 
        enabled: true
        register: true
        root: /cloud

management:
  endpoints:
    web:
      exposure:
        include: '*'

test.name: zhangsan
  