
logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 8889

spring:
  application:
    name: mrh-spring-boot-admin-client-cloud 
  cloud: 
    zookeeper: 
      enabled: true
      connect-string: localhost:2181
      prefer-ip-address: true
      max-retries: 10
      max-sleep-ms: 500
      discovery: 
        enabled: true
        register: true
        root: /cloud

management: 
  endpoints: 
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: '*'



