
logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 8888

spring:
  application:
    name: mrh-spring-boot-admin-client-boot 
  boot:
    admin:
      client:
        url: http://127.0.0.1:18888
        username: "admin"
        password: "123456"
        instance: 
          prefer-ip: true

management: 
  endpoints: 
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: '*'



