
seata:
  enabled: true
  # 关闭自动配置，手动配置代理数据源
  enable-auto-data-source-proxy: false
  application-id: mrh-seata-at-integral
  tx-service-group: default_tx_group
  data-source-proxy-mode: AT
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 192.168.140.130:8091
  client:
    rm-report-retry-count: 5
    rm-async-commit-buffer-limit: 10000
    tm-commit-retry-count: 5
    tm-rollback-retry-count: 20

