
# 日志配置
logging: 
  config: classpath:log4j2-spring.xml

# 容器配置
server: 
  port: 8888
  servlet: 
    context-path: /
    session.timeout: 0
  tomcat: 
    uri-encoding: UTF-8
    accept-count: 512
    min-spare-threads: 10
    max-connections: 10000
    max-threads: 500
    accesslog: 
      enabled: true
      buffered: true
      directory: /usr/local/logs/boot/data/es
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      request-attributes-enabled: true
      rotate: true
      suffix: .log
      background-processor-delay: 10s

# spring boot 配置
spring: 
  elasticsearch:
    uris: "http://192.168.140.195:9200"
    socket-timeout: "10s"
    restclient:
      sniffer:
        interval: 10m
        delay-after-failure: 30s
    repositories: 
      enabled: false


