
seata:
  enabled: true
  enable-auto-data-source-proxy: false
  application-id: mrh-seata-saga-user
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  client:
    rm-report-retry-count: 5
    rm-async-commit-buffer-limit: 10000
    tm-commit-retry-count: 5
    tm-rollback-retry-count: 20
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.140.130:8848
      application: seata-server
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
  saga:
    enabled: true
    state-machine:
      application-id: ${seata.application-id}
      resources: 'classpath:statelang/*.json'
      rm-report-success-enable: true
      saga-branch-register-enable: true
      saga-compensate-persist-mode-update: true
      saga-retry-persist-mode-update: true
