
# 日志配置
logging: 
  config: classpath:log4j2-spring.xml

# 容器配置
server: 
  port: 8888
  servlet: 
    context-path: /
    session.timeout: 0
  tomcat: 
    uri-encoding: UTF-8
    accept-count: 512
    min-spare-threads: 10
    max-connections: 10000
    max-threads: 500
    accesslog: 
      enabled: true
      buffered: true
      directory: /usr/local/logs/test
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      request-attributes-enabled: true
      rotate: true
      suffix: .log
      background-processor-delay: 10s

# spring boot 配置
spring: 
  mvc: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    servlet.load-on-startup: 1
    throw-exception-if-no-handler-found: true
  resources: 
    add-mappings: true
  jackson: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    joda-date-time-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
  servlet: 
    multipart: 
      enabled: true
      max-file-size: 20MB
      max-request-size: 24MB
      location: /usr/local/logs/test
  redis: 
    host: 127.0.0.1
    port: 6379
    timeout: 200ms
    pool: 
      max-active: 3000
      max-idle: 8

