
logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 9547
  servlet: 
    context-path: /

spring:
  application:
    name: mrh-spring-cloud-service-task
  jackson: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    joda-date-time-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization: 
      FAIL_ON_UNKNOWN_PROPERTIES: false
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    visibility:
      GETTER: NONE
      SETTER: NONE
      FIELD: ANY
  datasource: 
    url: 'jdbc:mysql://192.168.140.130:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8'
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2: 
      max-active: 1000
      initial-size: 5
      max-idle: 50
      max-wait: 60000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      remove-abandoned: true
      remove-abandoned-timeout: 180
  cloud: 
    zookeeper: 
      enabled: true
      connect-string: localhost:2181
      prefer-ip-address: true
      max-retries: 10
      max-sleep-ms: 500
      discovery: 
        enabled: true
        register: true
        root: /cloud
    task:
      name: task-test
      initialize-enabled: true
      single-instance-enabled: false
      closecontext-enabled: true





