
logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 9527
  servlet: 
    context-path: /

spring:
  application:
    name: mrh-spring-cloud-service-organ
  servlet: 
    multipart: 
      enabled: true
      max-file-size: 50MB
      max-request-size: 60MB
  mvc: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    servlet.load-on-startup: 1
    throw-exception-if-no-handler-found: true
  resources: 
    add-mappings: false
  jackson: 
    date-format: 'yyyy-MM-dd HH:mm:ss'
    joda-date-time-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization: 
      FAIL_ON_UNKNOWN_PROPERTIES: false
      READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    visibility:
      GETTER: NONE
      SETTER: NONE
      FIELD: ANY
  cloud: 
    zookeeper: 
      enabled: true
      connect-string: localhost:2181
      prefer-ip-address: true
      max-retries: 10
      max-sleep-ms: 500
      discovery: 
        enabled: true
        register: true
        root: /cloud
  sleuth:
    enabled: true
    trace-id128: false
    sampler:
      # 采样率 0-1 当前 0.1 为采样 10%
      probability: 0.1
      # 每秒最大采样数
      rate: 10
      refresh.enabled: false
  zipkin:
    enabled: true
    sender.type: WEB
    base-url: http://localhost:9411



