
logging: 
  config: classpath:log4j2-spring.xml

server: 
  port: 9002
  servlet: 
    context-path: /

spring:
  application:
    name: mrh-apache-dubbo-api-demo

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    id: zookeeper-registry
    address: zookeeper://127.0.0.1:2181


